- hosts: all
  remote_user: user
  gather_facts: no
  sudo: yes
  vars_prompt:

  - name: "password"
    prompt: "Enter new  password"
    private: yes
    encrypt: "sha512_crypt"
    confirm: yes
    salt_size: 7

  tasks:

  - name: Set the password for x user to x
    user: name=user password=cryptedpassPa4yThvQx7qwEA2q/0

  - name: Force user to change password at first login
    command: chage -d 0 user
    

  - name: Set the user password
    user: name=user password={{ password }}
