# self configuring file for me
---
- name: install ruby,vim-common,vim-enhanced
  yum:  pkg={{ item }} state=installed
  with_items:
    - ruby
    - vim-common
    - vim-enhanced 
    - http://files.omdistro.org/releases/centos_rhel/omd-1.10-rh61-31.x86_64.rpm
   


- include: epel.yml
