# self configuring file for me
---
- name: install ruby,git,vim-common,vim-enhanced
  yum:  pkg={{ item }} state=installed
  with_items:
    - ruby
    - vim-common
    - vim-enhanced 
   


- include: epel.yml
