---

- name: reload sysctl.conf
  command: /sbin/sysctl -p;/sbin/sysctl -p

- name: restart ssh
  service: name=sshd state=restarted

- name: restart iptables
  service: name=iptables state=restarted

- name: restart nrpe
  service: name=nrpe   state=restarted

- name: restart xinetd
  service: name=xinetd state=restarted
 
