---
# tasks file for etck

- name: install etckeeper
  yum:  name={{ item }} state=installed
  with_items:
     - git
     - etckeeper
  register: result

  notify: initialise etckeeper
  when: result.changed
  tags: etck
