# iocpre.yml

---
#########################
### IBM ioc pre-reqs  ###
#########################

- name: set net.ipv4.tcp_fin_timeout=15 (kernel parameter)
  sysctl: name=net.ipv4.tcp_fin_timeout value=15 state=present reload=yes
  when: ansible_distribution == "RedHat"
  tags:
    - iocpre


- name: /etc/security/limits.conf hard limit config
  lineinfile: dest=/etc/security/limits.conf
              state=present
              insertafter='^#@student        -'
              line='*               hard    nofile          20480'
  when: ansible_distribution == "RedHat"
  tags:
    - iocpre

- name: /etc/security/limits.conf soft limit config
  lineinfile: dest=/etc/security/limits.conf
              state=present
              insertafter='^#@student        -'
              line='*               soft    nofile          20480'
  when: ansible_distribution == "RedHat"
  tags:
    - iocpre


- name: extras (1) for /etc/security/limits.conf
  lineinfile: dest=/etc/security/limits.conf
              state=present
              insertafter='^# End of file'
              line='notes hard nofile 65535'
  when: role == "APP"
  
  tags:
    - iocpre

- name: extras (2) for /etc/security/limits.conf
  lineinfile: dest=/etc/security/limits.conf
              state=present
              insertafter='^# End of file'
              line='notes soft nofile 65535'
  when: role == "APP"
  tags:
    - iocpre


- name: /etc/security/limits.d/90-nproc.conf config
  copy: src=90-nproc.conf dest=/etc/security/limits.d/90-nproc.conf 
        owner=root group=root mode=644
  when: ansible_distribution == "RedHat"
  tags:
    - iocpre


#- name: ssh config test
#  lineinfile:
#    dest=/etc/ssh/sshd_config
#    state=present
#    regexp=^{{ item.key }}
#    line="{{ item.key }} {{ item.value }}"
#    insertafter=EOF
#  with_items:
#    - { key: 'PermitRootLogin', value: 'no' }
#    - { key: 'LoginGraceTime', value: '20' }
#    - { key: 'X11Forwarding', value: 'no' }
#    - { key: 'ClientAliveInterval', value: '30' }
#    - { key: 'ClientAliveCountMax', value: '1000' }
#  notify:
#    - restart ssh
#  tags:
#    - sshtest
########################
### END of iocs pre  ###
########################
