# file: roles/common/tasks/iptab.yml
---

- name: iptables configuration
  template: src=iptables.j2 dest=/etc/sysconfig/iptables owner=root group=root mode=0644
  notify: 
    - restart iptables
  tags:
    - iptables
