######################################################################
# Some configuration defaults which may overlap the kickstart file   #
# settings but which will help keep specific server settings in sync.#
######################################################################
---

- name: create .ssh dir for root user
  file: dest=/root/.ssh mode=700 owner=root group=root state=directory

- name: copy root public key to remote servers
  copy: src=../files/id_dsa.pub dest=/root/.ssh/authorized_keys 
        owner=root group=root mode=400 backup=yes


- name: motd template
  template: src=motd.j2 dest=/etc/motd owner=root group=root mode=644
  tags:
    - motd

- name: configure /etc/hosts file
  copy: src=hosts dest=/etc/hosts owner=root group=root mode=644
  tags:
    - hostfile




###########################################################################
# specific include files go here as so to keep this file cleaner/readable #
# #########################################################################

- include: logs.yml
- include: timelocale.yml
- include: iocpre.yml
