# main.yml - config for all common role servers goes in here..
#
######################################################################
# Some configuration defaults which may overlap the kickstart file   #
# settings but which will help keep specific server settings in sync.#
######################################################################
---

- name: configure /etc/hosts file
  template: src={{ item }} dest=/etc/hosts owner=root group=root mode=644
  with_first_found:
    - files:
       - hosts-{{ env }}.j2
       - hosts.j2
      paths:
       - /etc/ansible/roles/common/templates/
  tags:
    - hostfile
 

- name: configure message of the day 
  template: src={{ item }} dest=/etc/motd owner=root group=root mode=644
  with_first_found:
    - files:
       - motd-{{ env }}.j2
       - motd.j2
      paths:
       - /etc/ansible/roles/common/templates/
  tags:
    - motd


- name: add additional resolver
  lineinfile: dest=/etc/resolv.conf line="nameserver 10.220.10.2"
  tags: resolver


- name: copy vmware tools install script to /usr/bin
  copy: src=vmtools.py dest=/usr/bin/vmtools.py owner=root group=root mode=755
  tags:
    - vmtools


###########################################################################
# specific include files go here as so to keep this file cleaner/readable #
# #########################################################################

- include: pubkey.yml                   # root ssh pub key
- include: logs.yml                     # configure logs
- include: timelocale.yml               # configure time/locale
- include: iocpre.yml                   # ioc prerequisites
- include: rhelcustom.yml               # temp custom repo for redhat boxes
- include: extras.yml                   # additional packages
