# file: pubkey.yml
####################################################
# copy root public key pair to all servers         #
# this play must be run with the  -k or --ask-pass #
# flags to enable key auth from here on            #
####################################################

---

- name: Set up authorized keys for control management
  authorized_key: user=root key="{{ lookup('file', '/root/.ssh/id_dsa.pub') }}"

  tags:
    - pubkey

