# file: roles/common/tasks/rhelcustom.yml 
---

- name: create custom dag wiers rhel repo
  copy: src=rpmforge dest=/etc/yum.repos.d/rpmforge.repo
        owner=root group=root mode=0644
  tags: rpmforge 
