# file: roles/analytics/tasks/main.yml

---

- name: install KDE and X Windows
  yum:  name="{{ item }}" state=present
  with_items:
    - "@X Window System"
    - "@KDE Desktop"
  tags: rhelcustom
  when: role == "ANALYTICS"

- name: install screen
  yum:  name=screen state=present
  when: role == "ANALYTICS" 
  tags: rhelcustom
 
- name: copy pam.i686 and dependencies to dest server
  copy: src={{ item }} dest=/tmp/{{ item }}
  with_items:
    - pam-1.1.1-17.el6.i686.rpm
    - pam-devel-1.1.1-17.el6.i686.rpm
    - db4-4.7.25-18.el6_4.i686.rpm
    - cracklib-2.8.16-4.el6.i686.rpm
  when: role == "ANALYTICS"
  tags: rhelcustom

- name: force rpm install of pam.i686
  shell: /bin/rpm -ivh --force /tmp/{{ item }}; touch /tmp/pam_installed.txt
         creates=/tmp/pam_installed.txt
  with_items:
    - db4-4.7.25-18.el6_4.i686.rpm
    - cracklib-2.8.16-4.el6.i686.rpm
    - pam-devel-1.1.1-17.el6.i686.rpm
    - pam-1.1.1-17.el6.i686.rpm
  when: role == "ANALYTICS"
  tags: rhelcustom


- include: nfs.yml  
